### PR TITLE
Bug fix of configuration error in Symfony 3

### PR DESCRIPTION
**Pull request by AdamHornik**
Symfony 3 configuration error '->cannotBeEmpty() is not applicable to NumericNodeDefinition' fix

### CODE REVIEW

**Comment by AdamHornik** [comment]
You are welcome.

**Comment by AshleyDawson** [comment]
Forgot to mention, did you test backwards compatibility with Symfony 2.*?

**Comment by AdamHornik** [comment]
I tested it with Symfony 2.3.42 and it was working properly.

**Comment by AshleyDawson** [comment]
Perfect, cheers

**Pull request merged**
